Repository 4year/what-to-wear-today, pull requests merged in 2022-12, with the labels that each got.

#44 feat : 주간날씨 렌더링 => setInterval 추가
  package-lock.json
  package.json
  src/components/weather/WeeklyWeather.js
  src/pages/Loading.js
Labels: ✨ Feature

#45 Feat : 지역 검색 및 지역 목록 추가
  src/App.js
  src/cityList.json
  src/components/addLocation/SearchBar.js
  src/components/addLocation/SearchResult.js
  src/components/sideBar/CurrentLocation.js
  src/components/sideBar/Location.js
  src/components/sideBar/LocationList.js
  src/components/sideBar/SideBar.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/index.js
  src/pages/Home.js
  src/pages/Loading.js
  src/test.json
  src/utils/city/cityList.json
  src/utils/city/index.js
  src/utils/weather/WeatherData.js
  src/utils/weather/index.js
Labels: 🎨 Html&css, ✨ Feature

#48 Feat : 지역 목록 삭제 체크박스 기능
  src/components/Dresses.js
  src/components/Header.js
  src/components/sideBar/Location/LocationList.js
  src/components/sideBar/Location/RemoveLocaiotn.js
  src/components/sideBar/Location/SearchBar.js
  src/components/sideBar/Location/SearchResult.js
  src/components/sideBar/SideBar.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/pages/Home.js
  src/pages/Loading.js
Labels: ✨ Feature

#49 Style : scroll event 오류 해결
  src/components/sideBar/SideBar.js
  src/pages/Home.js
Labels: 🎨 Html&css, 🐞 BugFix

#50 feat : weeklyWeather 시간 수정
  src/components/weather/WeeklyWeather.js
  src/pages/Loading.js
Labels: ✨ Feature

#51 Feat : 첫 로딩 시 마지막 현재 위치로 렌더링 되게
  src/components/sideBar/Location/RemoveLocaiotn.js
  src/components/sideBar/SideBar.js
  src/pages/Home.js
  src/pages/Loading.js
Labels: ✨ Feature

#52 fix : currentCiity null 문제 해결
  package-lock.json
  src/pages/Loading.js
Labels: 🐞 BugFix

#53 Docs : og img, Read me 작성
  README.md
  package-lock.json
  public/images/og img 1.jpg
  public/images/og img 2.jpg
  public/images/오늘 뭐 입지?.jpg
  public/index.html
  src/components/weather/WeeklyWeather.js
Labels: 📃 Docs

#54 Deploy : 깃허브 배포
  package-lock.json
  package.json
  src/pages/Loading.js
Labels: 🌏 Deploy

#55 docs:og 수정
  public/images/what-wear.jpg
  public/index.html
Labels: 🌏 Deploy
