Repository 4year/what-to-wear-today, pull requests merged in 2022-11, with the labels that each got.

#11 Style/side bar
  package-lock.json
  package.json
  src/components/sideBar/Location.js
  src/components/sideBar/LocationList.js
  src/components/sideBar/SideBar.js
  src/components/sideBar/SideHeader.js
Labels: 🎨 Html&css

#13 Style : Weater Container 이미지 퍼블리싱 1차 완료
  package-lock.json
  package.json
  src/components/addLocation/SearchBar.js
  src/components/sideBar/SideBar.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/index.js
  src/pages/Loadging.js
  src/pages/scrollBar.js
Labels: 🎨 Html&css

#14 Style : 헤더 및 이미지 컨테이너 퍼블리싱 1차 완료
  public/images/a.js
  public/images/dresses/dress1.png
  public/images/dresses/dress2.png
  public/images/dresses/dress3.png
  public/images/dresses/dress4.png
  public/images/favicon.ico
  public/images/loading.gif
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/components/Clothes.js
  src/components/Dresses.js
  src/components/Header.js
  src/index.js
  src/pages/Home.js
  src/pages/Loadging.js
Labels: 🎨 Html&css

#16 feat : 현재 위치 찾기 기능, 현재 날씨 api 연동
  .gitignore
  src/App.js
  src/components/Dresses.js
  src/components/sideBar/Location.js
  src/components/sideBar/SideBar.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/index.js
  src/pages/Home.js
  src/test.js
  src/test.json
Labels: ✨ Feature

#21 Style : weather 컨테이너 배경 색 및 물결 모양 / Feat : 이미지 슬라이드
  package-lock.json
  src/App.js
  src/WeatherData.js
  src/components/Dresses.js
  src/components/weather/WeatherContainer.js
  src/index.js
  src/pages/Home.js
  src/utils/slide/index.js
  src/utils/slide/registaerDragEvent.js
Labels: 🎨 Html&css, ✨ Feature

#20 feat : side bar 기능 구현
  src/components/Header.js
  src/components/sideBar/Location.js
  src/components/sideBar/LocationList.js
  src/components/sideBar/SideBar.js
  src/components/sideBar/SideHeader.js
Labels: 🔨 Refactoring, ✨ Feature

#24 Style : App 전체적인 css 수정 / Fix : drag 이벤트 및 현재 날씨 로직 수정
  public/index.html
  src/App.js
  src/components/Dresses.js
  src/components/Header.js
  src/components/sideBar/SideBar.js
  src/components/sideBar/SideHeader.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/index.css
  src/index.js
  src/pages/Home.js
  src/test.json
  src/utils/drag/index.js
  src/utils/drag/registaerDragEvent.js
Labels: 🎨 Html&css, 🐞 BugFix, 🔨 Refactoring

#23 style : search bar 퍼블리싱
  src/App.js
  src/components/Header.js
  src/components/addLocation/SearchBar.js
  src/components/sideBar/CurrentLocation.js
  src/components/sideBar/SideBar.js
  src/components/sideBar/SideHeader.js
  src/pages/AddLocation.js
  src/pages/Home.js
  src/pages/Loading.js
Labels: 🎨 Html&css, ✨ Feature

#25 style : weekly container 퍼블리싱
  src/components/sideBar/SideBar.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/pages/Home.js
  src/weeklyTest.json
Labels: 🎨 Html&css, ✨ Feature

#26 Feat : Home 페이지 Drag Up 이벤트 추가
  public/images/wave.png
  src/App.js
  src/components/Dresses.js
  src/components/Header.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/pages/Home.js
  src/utils/drag.js
  src/utils/drag/index.js
Labels: 🎨 Html&css, ✨ Feature

#29 style : 사이드바 css 수정
  src/components/sideBar/SideBar.js
  src/pages/Home.js
Labels: 🎨 Html&css

#30 Fix : 사이드바 토글 기능 / Style : header 및 weather 컨테이너 css 수정
  src/components/Header.js
  src/components/sideBar/SideBar.js
  src/components/sideBar/SideHeader.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/index.css
  src/pages/Home.js
Labels: 🎨 Html&css, 🐞 BugFix

#31 style: weekly weather api 적용 완료
  src/.prettierrc
  src/App.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/pages/Home.js
  src/test.json
  src/weeklyTest.json
Labels: 🎨 Html&css, ✨ Feature

#32 Refact : Router 및 Prettier 설정
  .prettierrc
  src/App.js
  src/WeatherData.js
  src/components/Dresses.js
  src/components/Header.js
  src/components/addLocation/SearchBar.js
  src/components/addLocation/SearchResult.js
  src/components/sideBar/CurrentLocation.js
  src/components/sideBar/Location.js
  src/components/sideBar/LocationList.js
  src/components/sideBar/SideBar.js
  src/components/sideBar/SideHeader.js
  src/components/weather/WeatherContainer.js
  src/components/weather/WeeklyWeather.js
  src/index.js
  src/pages/AddLocation.js
  src/pages/Home.js
  src/pages/Loading.js
  src/utils/drag.js
Labels: ⚙ Setting, 🔨 Refactoring

#33 chore : 지역목록 데이터 추가
  src/cityList.json
Labels: ⚙ Setting

#38 Feat : 카카오 공유하기 기능 추가
  package-lock.json
  package.json
  public/images/dresses/11~9.png
  public/images/dresses/16~12.png
  public/images/dresses/19~17.png
  public/images/dresses/22~20.png
  public/images/dresses/22~20_2.png
  public/images/dresses/27~23.png
  public/images/dresses/27~23_2.png
  public/images/dresses/28.png
  public/images/dresses/4.png
  public/images/dresses/8~5.png
  public/images/dresses/8~5_2.png
  public/index.html
  src/WeatherData.js
  src/components/Dresses.js
  src/components/Header.js
  src/components/weather/WeatherContainer.js
  src/pages/Home.js
  src/pages/Loading.js
  src/utils/weather.js
Labels: 🐞 BugFix, 🔨 Refactoring, 📬 API, ✨ Feature

#39 feat : WeeklyWeather temp / temp-icon api 호출 완료
  src/components/weather/WeeklyWeather.js
  src/pages/Home.js
  src/pages/Loading.js
  src/test.js
  src/test.json
Labels: 🎨 Html&css, ✨ Feature

#40 feat : searchBar 필터링 기능 1차구현
  src/LocationListData.js
  src/components/addLocation/SearchBar.js
  src/components/addLocation/SearchResult.js
  src/components/sideBar/LocationList.js
  src/components/sideBar/SideBar.js
Labels: 🔨 Refactoring, ✨ Feature

#42 style : scroll-bar css 수정
  src/components/weather/WeeklyWeather.js
Labels: 🎨 Html&css
